# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/add_rabbit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_rabbit(object):
    def setupUi(self, Add_rabbit):
        Add_rabbit.setObjectName("Add_rabbit")
        Add_rabbit.resize(365, 520)
        self.centralwidget = QtWidgets.QWidget(Add_rabbit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.rabbit_litter = QtWidgets.QWidget()
        self.rabbit_litter.setObjectName("rabbit_litter")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.rabbit_litter)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_rabbit_litter_mother = QtWidgets.QLabel(self.rabbit_litter)
        self.label_rabbit_litter_mother.setObjectName("label_rabbit_litter_mother")
        self.gridLayout_2.addWidget(self.label_rabbit_litter_mother, 0, 0, 1, 1)
        self.comboBox_mother_rabbit_litter = QtWidgets.QComboBox(self.rabbit_litter)
        self.comboBox_mother_rabbit_litter.setObjectName("comboBox_mother_rabbit_litter")
        self.gridLayout_2.addWidget(self.comboBox_mother_rabbit_litter, 0, 1, 1, 4)
        self.label_rabbit_litter_arrive = QtWidgets.QLabel(self.rabbit_litter)
        self.label_rabbit_litter_arrive.setObjectName("label_rabbit_litter_arrive")
        self.gridLayout_2.addWidget(self.label_rabbit_litter_arrive, 1, 0, 1, 1)
        self.dateEdit_rabbit_litter_arrive = QtWidgets.QDateEdit(self.rabbit_litter)
        self.dateEdit_rabbit_litter_arrive.setObjectName("dateEdit_rabbit_litter_arrive")
        self.gridLayout_2.addWidget(self.dateEdit_rabbit_litter_arrive, 1, 1, 1, 2)
        self.label_count_rabbits_litter = QtWidgets.QLabel(self.rabbit_litter)
        self.label_count_rabbits_litter.setObjectName("label_count_rabbits_litter")
        self.gridLayout_2.addWidget(self.label_count_rabbits_litter, 2, 0, 1, 3)
        self.spinBox_count_rabbits_rabbit_litter = QtWidgets.QSpinBox(self.rabbit_litter)
        self.spinBox_count_rabbits_rabbit_litter.setObjectName("spinBox_count_rabbits_litter")
        self.gridLayout_2.addWidget(self.spinBox_count_rabbits_rabbit_litter, 2, 4, 1, 1)
        self.label_rabbit_litter_living = QtWidgets.QLabel(self.rabbit_litter)
        self.label_rabbit_litter_living.setObjectName("label_rabbit_litter_living")
        self.gridLayout_2.addWidget(self.label_rabbit_litter_living, 3, 0, 1, 1)
        self.spinBox_living_rabbit_litter = QtWidgets.QSpinBox(self.rabbit_litter)
        self.spinBox_living_rabbit_litter.setObjectName("spinBox_living_rabbit_litter")
        self.gridLayout_2.addWidget(self.spinBox_living_rabbit_litter, 3, 4, 2, 1)
        self.label_kukovanie = QtWidgets.QLabel(self.rabbit_litter)
        self.label_kukovanie.setObjectName("label_kukovanie")
        self.gridLayout_2.addWidget(self.label_kukovanie, 4, 0, 2, 1)
        self.label_27 = QtWidgets.QLabel(self.rabbit_litter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 6, 0, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.rabbit_litter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 6, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.rabbit_litter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 7, 0, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.rabbit_litter)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_2.addWidget(self.plainTextEdit_3, 8, 0, 1, 5)
        self.spinBox_kukovanie = QtWidgets.QSpinBox(self.rabbit_litter)
        self.spinBox_kukovanie.setReadOnly(False)
        self.spinBox_kukovanie.setAccelerated(False)
        self.spinBox_kukovanie.setMinimum(-99)
        self.spinBox_kukovanie.setObjectName("spinBox_kukovanie")
        self.gridLayout_2.addWidget(self.spinBox_kukovanie, 5, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.rabbit_litter)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 9, 2, 1, 3)
        self.tabWidget.addTab(self.rabbit_litter, "")
        self.From_outside = QtWidgets.QWidget()
        self.From_outside.setObjectName("From_outside")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.From_outside)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.From_outside)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.From_outside)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboBox_status2 = QtWidgets.QComboBox(self.From_outside)
        self.comboBox_status2.setObjectName("comboBox_status2")
        self.gridLayout_3.addWidget(self.comboBox_status2, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.From_outside)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.comboBox_gender_2 = QtWidgets.QComboBox(self.From_outside)
        self.comboBox_gender_2.setObjectName("comboBox_gender_2")
        self.gridLayout_3.addWidget(self.comboBox_gender_2, 2, 2, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.From_outside)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_3.addWidget(self.plainTextEdit_2, 11, 0, 1, 3)
        self.comboBox_mother = QtWidgets.QComboBox(self.From_outside)
        self.comboBox_mother.setObjectName("comboBox_mother")
        self.gridLayout_3.addWidget(self.comboBox_mother, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.From_outside)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 2)
        self.btn_save_2 = QtWidgets.QPushButton(self.From_outside)
        self.btn_save_2.setObjectName("btn_save_2")
        self.gridLayout_3.addWidget(self.btn_save_2, 12, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.From_outside)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 9, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.From_outside)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 8, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.From_outside)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 0, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.From_outside)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 9, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.From_outside)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 8, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.From_outside)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.From_outside)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 7, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.From_outside)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.From_outside)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 2)
        self.comboBox_okrol = QtWidgets.QComboBox(self.From_outside)
        self.comboBox_okrol.setObjectName("comboBox_okrol")
        self.gridLayout_3.addWidget(self.comboBox_okrol, 1, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.From_outside)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.From_outside)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 10, 0, 1, 1)
        self.lineEdit_from_rabbit_litter_line = QtWidgets.QLineEdit(self.From_outside)
        self.lineEdit_from_rabbit_litter_line.setObjectName("lineEdit_from_rabbit_litter_line")
        self.gridLayout_3.addWidget(self.lineEdit_from_rabbit_litter_line, 4, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.From_outside)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 4, 0, 1, 1)
        self.tabWidget.addTab(self.From_outside, "")
        self.Farm = QtWidgets.QWidget()
        self.Farm.setObjectName("Farm")
        self.gridLayout = QtWidgets.QGridLayout(self.Farm)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_status = QtWidgets.QComboBox(self.Farm)
        self.comboBox_status.setObjectName("comboBox_status")
        self.gridLayout.addWidget(self.comboBox_status, 9, 1, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Farm)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 11, 0, 1, 3)
        self.dateEdit = QtWidgets.QDateEdit(self.Farm)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 2)
        self.btn_save_3 = QtWidgets.QPushButton(self.Farm)
        self.btn_save_3.setObjectName("btn_save_3")
        self.gridLayout.addWidget(self.btn_save_3, 12, 1, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Farm)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.Farm)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBox_gender_1 = QtWidgets.QComboBox(self.Farm)
        self.comboBox_gender_1.setObjectName("comboBox_gender_1")
        self.gridLayout.addWidget(self.comboBox_gender_1, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.Farm)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Farm)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 8, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Farm)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Farm)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Farm)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Farm)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 9, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.Farm)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 8, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Farm)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.Farm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.Farm)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.Farm)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Farm)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 6, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.Farm)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Farm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Farm)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Farm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Farm, "")
        self.verticalLayout.addWidget(self.tabWidget)
        Add_rabbit.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Add_rabbit)
        self.statusbar.setObjectName("statusbar")
        Add_rabbit.setStatusBar(self.statusbar)

        self.retranslateUi(Add_rabbit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Add_rabbit)

    def retranslateUi(self, Add_rabbit):
        _translate = QtCore.QCoreApplication.translate
        Add_rabbit.setWindowTitle(_translate("Add_rabbit", "MainWindow"))
        self.label_rabbit_litter_mother.setText(_translate("Add_rabbit", "Крольчиха:"))
        self.label_rabbit_litter_arrive.setText(_translate("Add_rabbit", "Дата окрола:"))
        self.label_count_rabbits_litter.setText(_translate("Add_rabbit", "Количество крольчат в помёте:"))
        self.label_rabbit_litter_living.setText(_translate("Add_rabbit", "Выжило:"))
        self.label_kukovanie.setText(_translate("Add_rabbit", "Кукование:"))
        self.label_27.setText(_translate("Add_rabbit", "Кроликов в гнезде: "))
        self.label_28.setText(_translate("Add_rabbit", "задать кол"))
        self.label_29.setText(_translate("Add_rabbit", "Заметки:"))
        self.pushButton.setText(_translate("Add_rabbit", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rabbit_litter), _translate("Add_rabbit", "Помёт"))
        self.label_23.setText(_translate("Add_rabbit", "Возвраст"))
        self.label_11.setText(_translate("Add_rabbit", "Окрол:"))
        self.label_10.setText(_translate("Add_rabbit", "Мать:"))
        self.label_13.setText(_translate("Add_rabbit", "Дата рождения:"))
        self.btn_save_2.setText(_translate("Add_rabbit", "Сохранить"))
        self.label_17.setText(_translate("Add_rabbit", "Помещен в клетку №:"))
        self.label_16.setText(_translate("Add_rabbit", "Средний привес:"))
        self.label_20.setText(_translate("Add_rabbit", "Крайний вес:"))
        self.label_19.setText(_translate("Add_rabbit", "в средним весил"))
        self.label_26.setText(_translate("Add_rabbit", "Статус:"))
        self.label_21.setText(_translate("Add_rabbit", "посл. весллллл"))
        self.label_15.setText(_translate("Add_rabbit", "Возвраст:"))
        self.label_12.setText(_translate("Add_rabbit", "Пол кролика:"))
        self.label_14.setText(_translate("Add_rabbit", "Ввести дату"))
        self.label_25.setText(_translate("Add_rabbit", "Заметки:"))
        self.label_30.setText(_translate("Add_rabbit", "Линия:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.From_outside), _translate("Add_rabbit", "Из помета "))
        self.btn_save_3.setText(_translate("Add_rabbit", "Сохранить"))
        self.label_6.setText(_translate("Add_rabbit", "Линия:"))
        self.label_9.setText(_translate("Add_rabbit", "задать дату"))
        self.label_22.setText(_translate("Add_rabbit", "Помещен в клетку №:"))
        self.label_5.setText(_translate("Add_rabbit", "Мать:"))
        self.label_7.setText(_translate("Add_rabbit", "Откуда"))
        self.label_24.setText(_translate("Add_rabbit", "Статус:"))
        self.label_2.setText(_translate("Add_rabbit", "Поступил в хозяйство"))
        self.label_4.setText(_translate("Add_rabbit", "Отец:"))
        self.label_8.setText(_translate("Add_rabbit", "Заметки:"))
        self.label_3.setText(_translate("Add_rabbit", "Пол Кролика:"))
        self.label_18.setText(_translate("Add_rabbit", "Вес:"))
        self.label.setText(_translate("Add_rabbit", "Дата рождения:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Farm), _translate("Add_rabbit", "Из другого хозяйства"))
