# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/change_data.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_data(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.id_rabbit = QtWidgets.QLabel(self.centralwidget)
        self.id_rabbit.setObjectName("id_rabbit")
        self.gridLayout.addWidget(self.id_rabbit, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_gender = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.gridLayout.addWidget(self.comboBox_gender, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateEdit_arrive = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_arrive.setObjectName("dateEdit_arrive")
        self.gridLayout.addWidget(self.dateEdit_arrive, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_mather = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mather.setObjectName("lineEdit_mather")
        self.gridLayout.addWidget(self.lineEdit_mather, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_father = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_father.setObjectName("lineEdit_father")
        self.gridLayout.addWidget(self.lineEdit_father, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_line.setObjectName("lineEdit_line")
        self.gridLayout.addWidget(self.lineEdit_line, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.spinBox_cell_number = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cell_number.setObjectName("spinBox_cell_number")
        self.gridLayout.addWidget(self.spinBox_cell_number, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.doubleSpinBox_weight = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_weight.setObjectName("doubleSpinBox_weight")
        self.gridLayout.addWidget(self.doubleSpinBox_weight, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.comboBox_status = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_status.setObjectName("comboBox_status")
        self.gridLayout.addWidget(self.comboBox_status, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.plainTextEdit_note = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_note.setObjectName("plainTextEdit_note")
        self.gridLayout.addWidget(self.plainTextEdit_note, 9, 1, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 10, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Кролик:"))
        self.id_rabbit.setText(_translate("MainWindow", "Id кролика"))
        self.label_9.setText(_translate("MainWindow", "Пол:"))
        self.label_3.setText(_translate("MainWindow", "Родился"))
        self.label_4.setText(_translate("MainWindow", "Мать:"))
        self.label_6.setText(_translate("MainWindow", "Отец:"))
        self.label_5.setText(_translate("MainWindow", "Линия:"))
        self.label_7.setText(_translate("MainWindow", "В клетке №"))
        self.label_8.setText(_translate("MainWindow", "Вес кролика:"))
        self.label_11.setText(_translate("MainWindow", "Статус:"))
        self.label_10.setText(_translate("MainWindow", "Заметка:"))
        self.pushButton_save.setText(_translate("MainWindow", "Сохранить"))
