# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/kill_rabbit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kill_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 251)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_rabbit = QtWidgets.QComboBox(self.tab)
        self.comboBox_rabbit.setObjectName("comboBox_rabbit")
        self.gridLayout_2.addWidget(self.comboBox_rabbit, 1, 0, 1, 2)
        self.btn_save_rabbit = QtWidgets.QPushButton(self.tab)
        self.btn_save_rabbit.setObjectName("btn_save_rabbit")
        self.gridLayout_2.addWidget(self.btn_save_rabbit, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.doubleSpinBox_rabbit = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_rabbit.setObjectName("doubleSpinBox_rabbit")
        self.gridLayout_2.addWidget(self.doubleSpinBox_rabbit, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_save_nest = QtWidgets.QPushButton(self.tab_2)
        self.btn_save_nest.setObjectName("btn_save_nest")
        self.gridLayout_3.addWidget(self.btn_save_nest, 5, 4, 1, 1)
        self.comboBox_nest = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_nest.setObjectName("comboBox_nest")
        self.gridLayout_3.addWidget(self.comboBox_nest, 1, 0, 1, 5)
        self.doubleSpinBox4 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox4.setSingleStep(0.1)
        self.doubleSpinBox4.setObjectName("doubleSpinBox4")
        self.gridLayout_3.addWidget(self.doubleSpinBox4, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.doubleSpinBox5 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox5.setSingleStep(0.1)
        self.doubleSpinBox5.setObjectName("doubleSpinBox5")
        self.gridLayout_3.addWidget(self.doubleSpinBox5, 3, 4, 1, 1)
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox2.setSingleStep(0.1)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.gridLayout_3.addWidget(self.doubleSpinBox2, 3, 1, 1, 1)
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox1.setSingleStep(0.1)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.gridLayout_3.addWidget(self.doubleSpinBox1, 3, 0, 1, 1)
        self.doubleSpinBox3 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox3.setSingleStep(0.1)
        self.doubleSpinBox3.setObjectName("doubleSpinBox3")
        self.gridLayout_3.addWidget(self.doubleSpinBox3, 3, 2, 1, 1)
        self.doubleSpinBox6 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox6.setSingleStep(0.1)
        self.doubleSpinBox6.setObjectName("doubleSpinBox6")
        self.gridLayout_3.addWidget(self.doubleSpinBox6, 4, 0, 1, 1)
        self.doubleSpinBox7 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox7.setSingleStep(0.1)
        self.doubleSpinBox7.setObjectName("doubleSpinBox7")
        self.gridLayout_3.addWidget(self.doubleSpinBox7, 4, 1, 1, 1)
        self.doubleSpinBox8 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox8.setSingleStep(0.1)
        self.doubleSpinBox8.setObjectName("doubleSpinBox8")
        self.gridLayout_3.addWidget(self.doubleSpinBox8, 4, 2, 1, 1)
        self.doubleSpinBox9 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox9.setSingleStep(0.1)
        self.doubleSpinBox9.setObjectName("doubleSpinBox9")
        self.gridLayout_3.addWidget(self.doubleSpinBox9, 4, 3, 1, 1)
        self.doubleSpinBox10 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox10.setSingleStep(0.1)
        self.doubleSpinBox10.setObjectName("doubleSpinBox10")
        self.gridLayout_3.addWidget(self.doubleSpinBox10, 4, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_o_kg = QtWidgets.QLabel(self.tab_2)
        self.label_o_kg.setObjectName("label_o_kg")
        self.gridLayout_3.addWidget(self.label_o_kg, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_sr_kg = QtWidgets.QLabel(self.tab_2)
        self.label_sr_kg.setObjectName("label_sr_kg")
        self.gridLayout_3.addWidget(self.label_sr_kg, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Кролик:"))
        self.btn_save_rabbit.setText(_translate("MainWindow", "Сохранить"))
        self.label_3.setText(_translate("MainWindow", "Вес туши:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Кролика"))
        self.btn_save_nest.setText(_translate("MainWindow", "Сохранить"))
        self.label_2.setText(_translate("MainWindow", "Гнездо:"))
        self.label_4.setText(_translate("MainWindow", "Вес тушек:"))
        self.label_5.setText(_translate("MainWindow", "Общий:"))
        self.label_o_kg.setText(_translate("MainWindow", "Об.кг"))
        self.label_7.setText(_translate("MainWindow", "Средний:"))
        self.label_sr_kg.setText(_translate("MainWindow", "ср.кг."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Гнездо"))
