# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/main_window2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(880, 480)  # 640x480
        self.centralwidget = QtWidgets.QWidget(Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabble_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabble_widget.setObjectName("tabble_widget")
        self.farm = QtWidgets.QWidget()
        self.farm.setObjectName("farm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.farm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.farm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 328, 116))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.btn_hide_done = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_hide_done.setObjectName("btn_hide_done")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_hide_done)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 5, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.farm)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget, 5, 0, 1, 5)
        self.btn_add_rabbit = QtWidgets.QPushButton(self.farm)
        self.btn_add_rabbit.setObjectName("btn_add_rabbit")
        self.gridLayout_5.addWidget(self.btn_add_rabbit, 0, 1, 1, 1)
        self.btn_write_off = QtWidgets.QPushButton(self.farm)
        self.btn_write_off.setObjectName("btn_write_off")
        self.gridLayout_5.addWidget(self.btn_write_off, 0, 2, 1, 1)
        self.btn_transplanted = QtWidgets.QPushButton(self.farm)
        self.btn_transplanted.setObjectName("btn_transplanted")
        self.gridLayout_5.addWidget(self.btn_transplanted, 0, 3, 1, 1)
        self.btn_killing = QtWidgets.QPushButton(self.farm)
        self.btn_killing.setObjectName("btn_killing")
        self.gridLayout_5.addWidget(self.btn_killing, 3, 2, 1, 1)
        self.btn_copulation = QtWidgets.QPushButton(self.farm)
        self.btn_copulation.setObjectName("btn_copulation")
        self.gridLayout_5.addWidget(self.btn_copulation, 2, 1, 1, 1)
        self.table_selection = QtWidgets.QComboBox(self.farm)
        self.table_selection.setObjectName("table_selection")
        self.gridLayout_5.addWidget(self.table_selection, 4, 1, 1, 3)
        self.btn_graft = QtWidgets.QPushButton(self.farm)
        self.btn_graft.setObjectName("btn_graft")
        self.gridLayout_5.addWidget(self.btn_graft, 3, 1, 1, 1)
        self.btn_setting = QtWidgets.QPushButton(self.farm)
        self.btn_setting.setObjectName("btn_setting")
        self.gridLayout_5.addWidget(self.btn_setting, 3, 3, 1, 1)
        self.btn_weigh = QtWidgets.QPushButton(self.farm)
        self.btn_weigh.setObjectName("btn_weigh")
        self.gridLayout_5.addWidget(self.btn_weigh, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.farm)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 2, 3, 1, 1)
        self.tabble_widget.addTab(self.farm, "")
        self.finance = QtWidgets.QWidget()
        self.finance.setObjectName("finance")
        self.tabble_widget.addTab(self.finance, "")
        self.gridLayout_3.addWidget(self.tabble_widget, 0, 0, 1, 1)
        Main_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        self.tabble_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.btn_hide_done.setText(_translate("Main_Window", "Скрыть выполненное"))
        self.checkBox.setText(_translate("Main_Window", "CheckBox"))
        self.btn_add_rabbit.setText(_translate("Main_Window", "Добавить"))
        self.btn_write_off.setText(_translate("Main_Window", "Списать"))
        self.btn_transplanted.setText(_translate("Main_Window", "Пересадил"))
        self.btn_killing.setText(_translate("Main_Window", "Забой"))
        self.btn_copulation.setText(_translate("Main_Window", "Случил"))
        self.btn_graft.setText(_translate("Main_Window", "Прививки"))
        self.btn_setting.setText(_translate("Main_Window", "Настройка"))
        self.btn_weigh.setText(_translate("Main_Window", "Взвесил"))
        self.pushButton_2.setText(_translate("Main_Window", "Статусы"))
        self.tabble_widget.setTabText(self.tabble_widget.indexOf(self.farm), _translate("Main_Window", "Ферма"))
        self.tabble_widget.setTabText(self.tabble_widget.indexOf(self.finance), _translate("Main_Window", "Финансы"))
