# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/main_window7.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(818, 500)
        self.centralwidget = QtWidgets.QWidget(Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabble_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabble_widget.setObjectName("tabble_widget")
        self.farm = QtWidgets.QWidget()
        self.farm.setObjectName("farm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.farm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_hide_done = QtWidgets.QPushButton(self.farm)
        self.btn_hide_done.setObjectName("btn_hide_done")
        self.gridLayout_5.addWidget(self.btn_hide_done, 5, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.farm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 211))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 6, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.farm)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget, 6, 0, 1, 6)
        self.btn_add_rabbit = QtWidgets.QPushButton(self.farm)
        self.btn_add_rabbit.setObjectName("btn_add_rabbit")
        self.gridLayout_5.addWidget(self.btn_add_rabbit, 0, 2, 1, 1)
        self.btn_write_off = QtWidgets.QPushButton(self.farm)
        self.btn_write_off.setObjectName("btn_write_off")
        self.gridLayout_5.addWidget(self.btn_write_off, 0, 3, 1, 1)
        self.btn_transplanted = QtWidgets.QPushButton(self.farm)
        self.btn_transplanted.setObjectName("btn_transplanted")
        self.gridLayout_5.addWidget(self.btn_transplanted, 0, 4, 1, 1)
        self.btn_killing = QtWidgets.QPushButton(self.farm)
        self.btn_killing.setObjectName("btn_killing")
        self.gridLayout_5.addWidget(self.btn_killing, 3, 3, 1, 1)
        self.btn_copulation = QtWidgets.QPushButton(self.farm)
        self.btn_copulation.setObjectName("btn_copulation")
        self.gridLayout_5.addWidget(self.btn_copulation, 2, 2, 1, 1)
        self.btn_graft = QtWidgets.QPushButton(self.farm)
        self.btn_graft.setObjectName("btn_graft")
        self.gridLayout_5.addWidget(self.btn_graft, 3, 2, 1, 1)
        self.btn_setting = QtWidgets.QPushButton(self.farm)
        self.btn_setting.setObjectName("btn_setting")
        self.gridLayout_5.addWidget(self.btn_setting, 3, 4, 1, 1)
        self.btn_weigh = QtWidgets.QPushButton(self.farm)
        self.btn_weigh.setObjectName("btn_weigh")
        self.gridLayout_5.addWidget(self.btn_weigh, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.farm)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.table_selection = QtWidgets.QComboBox(self.farm)
        self.table_selection.setObjectName("table_selection")
        self.gridLayout_5.addWidget(self.table_selection, 5, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 4, 2, 1, 1)
        self.tabble_widget.addTab(self.farm, "")
        self.finance = QtWidgets.QWidget()
        self.finance.setObjectName("finance")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.finance)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.finance)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_money = QtWidgets.QDoubleSpinBox(self.finance)
        self.doubleSpinBox_money.setMinimum(-99999.99)
        self.doubleSpinBox_money.setMaximum(99999.99)
        self.doubleSpinBox_money.setSingleStep(100.0)
        self.doubleSpinBox_money.setObjectName("doubleSpinBox_money")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_money)
        self.label_3 = QtWidgets.QLabel(self.finance)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_categories = QtWidgets.QComboBox(self.finance)
        self.comboBox_categories.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_categories.sizePolicy().hasHeightForWidth())
        self.comboBox_categories.setSizePolicy(sizePolicy)
        self.comboBox_categories.setMaxVisibleItems(10)
        self.comboBox_categories.setObjectName("comboBox_categories")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_categories)
        self.label_4 = QtWidgets.QLabel(self.finance)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_TheNote = QtWidgets.QLineEdit(self.finance)
        self.lineEdit_TheNote.setObjectName("lineEdit_TheNote")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_TheNote)
        self.btn_save_finance = QtWidgets.QPushButton(self.finance)
        self.btn_save_finance.setObjectName("btn_save_finance")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btn_save_finance)
        self.toolButton = QtWidgets.QToolButton(self.finance)
        self.toolButton.setObjectName("toolButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.toolButton)
        self.label_5 = QtWidgets.QLabel(self.finance)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_diagram = QtWidgets.QComboBox(self.finance)
        self.comboBox_diagram.setObjectName("comboBox_diagram")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_diagram)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.widget_for_pie = QtWidgets.QWidget(self.finance)
        self.widget_for_pie.setObjectName("widget_for_pie")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget_for_pie)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.tableWidget_money = QtWidgets.QTableWidget(self.finance)
        self.tableWidget_money.setObjectName("tableWidget_money")
        self.tableWidget_money.setColumnCount(0)
        self.tableWidget_money.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_money)
        self.tabble_widget.addTab(self.finance, "")
        self.gridLayout_3.addWidget(self.tabble_widget, 0, 1, 1, 1)
        Main_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        self.tabble_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.btn_hide_done.setText(_translate("Main_Window", "Обновить"))
        self.btn_add_rabbit.setText(_translate("Main_Window", "Добавить"))
        self.btn_write_off.setText(_translate("Main_Window", "Списать"))
        self.btn_transplanted.setText(_translate("Main_Window", "Пересадил"))
        self.btn_killing.setText(_translate("Main_Window", "Забой"))
        self.btn_copulation.setText(_translate("Main_Window", "Случил"))
        self.btn_graft.setText(_translate("Main_Window", "Прививки"))
        self.btn_setting.setText(_translate("Main_Window", "Настройка"))
        self.btn_weigh.setText(_translate("Main_Window", "Взвесил"))
        self.pushButton_2.setText(_translate("Main_Window", "Статусы"))
        self.tabble_widget.setTabText(self.tabble_widget.indexOf(self.farm), _translate("Main_Window", "Ферма"))
        self.label_2.setText(_translate("Main_Window", "Сумма:"))
        self.label_3.setText(_translate("Main_Window", "Категория:"))
        self.label_4.setText(_translate("Main_Window", "Заметка:"))
        self.btn_save_finance.setText(_translate("Main_Window", "Сохранить"))
        self.toolButton.setText(_translate("Main_Window", "..."))
        self.label_5.setText(_translate("Main_Window", "Таблицы:"))
        self.tabble_widget.setTabText(self.tabble_widget.indexOf(self.finance), _translate("Main_Window", "Финансы"))
