# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/mass.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_weigh_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mass_one = QtWidgets.QWidget()
        self.mass_one.setObjectName("mass_one")
        self.gridLayout = QtWidgets.QGridLayout(self.mass_one)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.mass_one)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.mass_one)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.mass_one)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.btn_mass1_save = QtWidgets.QPushButton(self.mass_one)
        self.btn_mass1_save.setObjectName("btn_mass1_save")
        self.gridLayout.addWidget(self.btn_mass1_save, 3, 2, 1, 1)
        self.doubleSpinBox_mass1 = QtWidgets.QDoubleSpinBox(self.mass_one)
        self.doubleSpinBox_mass1.setSingleStep(0.1)
        self.doubleSpinBox_mass1.setObjectName("doubleSpinBox_mass1")
        self.gridLayout.addWidget(self.doubleSpinBox_mass1, 2, 1, 1, 1)
        self.tabWidget.addTab(self.mass_one, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_nest_mother = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_nest_mother.setObjectName("comboBox_nest_mother")
        self.gridLayout_3.addWidget(self.comboBox_nest_mother, 0, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.comboBox_nest_nest = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_nest_nest.setObjectName("comboBox_nest_nest")
        self.gridLayout_3.addWidget(self.comboBox_nest_nest, 1, 1, 1, 3)
        self.btn_nest_save = QtWidgets.QPushButton(self.tab_2)
        self.btn_nest_save.setObjectName("btn_nest_save")
        self.gridLayout_3.addWidget(self.btn_nest_save, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_nest_srm = QtWidgets.QLabel(self.tab_2)
        self.label_nest_srm.setObjectName("label_nest_srm")
        self.gridLayout_3.addWidget(self.label_nest_srm, 4, 2, 1, 1)
        self.spinBox_count_nest = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_count_nest.setObjectName("spinBox_count_nest")
        self.gridLayout_3.addWidget(self.spinBox_count_nest, 2, 2, 1, 1)
        self.doubleSpinBox_mass_nest = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_mass_nest.setSingleStep(0.1)
        self.doubleSpinBox_mass_nest.setObjectName("doubleSpinBox_mass_nest")
        self.gridLayout_3.addWidget(self.doubleSpinBox_mass_nest, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.doubleSpinBox3 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox3.setSingleStep(0.1)
        self.doubleSpinBox3.setObjectName("doubleSpinBox3")
        self.gridLayout_8.addWidget(self.doubleSpinBox3, 2, 2, 1, 1)
        self.doubleSpinBox10 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox10.setSingleStep(0.1)
        self.doubleSpinBox10.setObjectName("doubleSpinBox10")
        self.gridLayout_8.addWidget(self.doubleSpinBox10, 3, 4, 1, 1)
        self.doubleSpinBox7 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox7.setSingleStep(0.1)
        self.doubleSpinBox7.setObjectName("doubleSpinBox7")
        self.gridLayout_8.addWidget(self.doubleSpinBox7, 3, 1, 1, 1)
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox1.setSingleStep(0.1)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.gridLayout_8.addWidget(self.doubleSpinBox1, 2, 0, 1, 1)
        self.doubleSpinBox8 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox8.setSingleStep(0.1)
        self.doubleSpinBox8.setObjectName("doubleSpinBox8")
        self.gridLayout_8.addWidget(self.doubleSpinBox8, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 1, 0, 1, 1)
        self.btn_nest1_save = QtWidgets.QPushButton(self.tab)
        self.btn_nest1_save.setObjectName("btn_nest1_save")
        self.gridLayout_8.addWidget(self.btn_nest1_save, 7, 3, 1, 2)
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox2.setSingleStep(0.1)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.gridLayout_8.addWidget(self.doubleSpinBox2, 2, 1, 1, 1)
        self.doubleSpinBox5 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox5.setSingleStep(0.1)
        self.doubleSpinBox5.setObjectName("doubleSpinBox5")
        self.gridLayout_8.addWidget(self.doubleSpinBox5, 2, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 6, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 0, 0, 1, 1)
        self.comboBox_nest1_nest = QtWidgets.QComboBox(self.tab)
        self.comboBox_nest1_nest.setObjectName("comboBox_nest1_nest")
        self.gridLayout_8.addWidget(self.comboBox_nest1_nest, 1, 1, 1, 4)
        self.comboBox_nest1_mother = QtWidgets.QComboBox(self.tab)
        self.comboBox_nest1_mother.setObjectName("comboBox_nest1_mother")
        self.gridLayout_8.addWidget(self.comboBox_nest1_mother, 0, 1, 1, 4)
        self.doubleSpinBox9 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox9.setSingleStep(0.1)
        self.doubleSpinBox9.setObjectName("doubleSpinBox9")
        self.gridLayout_8.addWidget(self.doubleSpinBox9, 3, 3, 1, 1)
        self.doubleSpinBox6 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox6.setSingleStep(0.1)
        self.doubleSpinBox6.setObjectName("doubleSpinBox6")
        self.gridLayout_8.addWidget(self.doubleSpinBox6, 3, 0, 1, 1)
        self.doubleSpinBox4 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox4.setSingleStep(0.1)
        self.doubleSpinBox4.setObjectName("doubleSpinBox4")
        self.gridLayout_8.addWidget(self.doubleSpinBox4, 2, 3, 1, 1)
        self.label_nest1_srm = QtWidgets.QLabel(self.tab)
        self.label_nest1_srm.setObjectName("label_nest1_srm")
        self.gridLayout_8.addWidget(self.label_nest1_srm, 6, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 4, 0, 1, 2)
        self.spinBox_nest1_count = QtWidgets.QSpinBox(self.tab)
        self.spinBox_nest1_count.setObjectName("spinBox_nest1_count")
        self.gridLayout_8.addWidget(self.spinBox_nest1_count, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_all_mass = QtWidgets.QLabel(self.tab)
        self.label_all_mass.setObjectName("label_all_mass")
        self.gridLayout_8.addWidget(self.label_all_mass, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Вес :"))
        self.label_4.setText(_translate("MainWindow", "Выбрать кролика"))
        self.btn_mass1_save.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mass_one), _translate("MainWindow", "Одного"))
        self.label_7.setText(_translate("MainWindow", "Общий вес:"))
        self.btn_nest_save.setText(_translate("MainWindow", "Сохранить"))
        self.label_3.setText(_translate("MainWindow", "Гнездо:"))
        self.label_2.setText(_translate("MainWindow", "Самка:"))
        self.label_nest_srm.setText(_translate("MainWindow", "вес кг"))
        self.label_8.setText(_translate("MainWindow", "Средний вес кролика:"))
        self.label_6.setText(_translate("MainWindow", "Количество кроликов:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Гнездо  "))
        self.label_26.setText(_translate("MainWindow", "Гнездо:"))
        self.btn_nest1_save.setText(_translate("MainWindow", "Сохранить"))
        self.label_27.setText(_translate("MainWindow", "Средний вес кролика:"))
        self.label_25.setText(_translate("MainWindow", "Самка:"))
        self.label_nest1_srm.setText(_translate("MainWindow", "вес кг"))
        self.label_28.setText(_translate("MainWindow", "Количество кроликов:"))
        self.label_9.setText(_translate("MainWindow", "Общий вес :"))
        self.label_all_mass.setText(_translate("MainWindow", "всего кг"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Гнездо по одному"))
