# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spock/PycharmProjects/KiberKrolik/vaccination.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vaccination(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_vaccine = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_vaccine.setObjectName("lineEdit_vaccine")
        self.gridLayout_2.addWidget(self.lineEdit_vaccine, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.dateEdit_rabbit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_rabbit.setObjectName("dateEdit_rabbit")
        self.gridLayout_2.addWidget(self.dateEdit_rabbit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_rabbit = QtWidgets.QComboBox(self.tab)
        self.comboBox_rabbit.setObjectName("comboBox_rabbit")
        self.gridLayout_2.addWidget(self.comboBox_rabbit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateEdit_next_vaccine = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_next_vaccine.setObjectName("dateEdit_next_vaccine")
        self.gridLayout_2.addWidget(self.dateEdit_next_vaccine, 3, 1, 1, 1)
        self.btn_save_rabbit = QtWidgets.QPushButton(self.tab)
        self.btn_save_rabbit.setObjectName("btn_save_rabbit")
        self.gridLayout_2.addWidget(self.btn_save_rabbit, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.dateEdit_nest_next = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit_nest_next.setObjectName("dateEdit_nest_next")
        self.gridLayout_3.addWidget(self.dateEdit_nest_next, 3, 1, 1, 1)
        self.comboBox_nest = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_nest.setObjectName("comboBox_nest")
        self.gridLayout_3.addWidget(self.comboBox_nest, 1, 1, 1, 1)
        self.dateEdit_nest = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit_nest.setObjectName("dateEdit_nest")
        self.gridLayout_3.addWidget(self.dateEdit_nest, 0, 1, 1, 1)
        self.lineEdit_nest = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_nest.setObjectName("lineEdit_nest")
        self.gridLayout_3.addWidget(self.lineEdit_nest, 2, 1, 1, 1)
        self.btn_save_nest = QtWidgets.QPushButton(self.tab_2)
        self.btn_save_nest.setObjectName("btn_save_nest")
        self.gridLayout_3.addWidget(self.btn_save_nest, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Дата прививки:"))
        self.label_4.setText(_translate("MainWindow", "Следующая:"))
        self.label_2.setText(_translate("MainWindow", "Кролик:"))
        self.label_3.setText(_translate("MainWindow", "Прививка:"))
        self.btn_save_rabbit.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Кролик"))
        self.label_6.setText(_translate("MainWindow", "Гнездо:"))
        self.label_7.setText(_translate("MainWindow", "Прививка:"))
        self.label_5.setText(_translate("MainWindow", "Дата прививки:"))
        self.label_8.setText(_translate("MainWindow", "Следующая:"))
        self.btn_save_nest.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Гнездо"))
